name: Hartmann Flow Model Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: dedalus_env
        auto-activate-base: false

    - name: Install system dependencies
      shell: bash -l {0}
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev libfftw3-dev libhdf5-dev

    - name: Install Dedalus 2 and dependencies
      shell: bash -l {0}
      run: |
        conda install -c conda-forge "dedalus<3.0" mpi4py h5py fftw matplotlib numpy scipy -y
        pip install pytest pytest-xdist

    - name: List directory contents
      shell: bash -l {0}
      run: ls -R

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest -v tests/test_exec.py


