name: Hartmann Flow Model Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev libfftw3-dev libhdf5-dev

    - name: Set environment variables to disable threading
      run: |
        conda env config vars set OMP_NUM_THREADS=1
        conda env config vars set NUMEXPR_MAX_THREADS=1

    - name: Create and activate conda environment
      run: |
        conda create -n dedalus-env python=${{ matrix.python-version }} -y
        echo "conda activate dedalus-env" >> $GITHUB_ENV

    - name: Install Dedalus and dependencies
      run: |
        conda activate dedalus_env
        conda install -c conda-forge dedalus mpi4py h5py fftw -y

    - name: Install pytest and pytest-xdist
      run: |
        conda activate dedalus_env
        pip install pytest pytest-xdist

    - name: Run tests
      run: |
        conda activate dedalus_env
        pytest -n auto




