
name: Hartmann Flow Model Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev libfftw3-dev libhdf5-dev

    - name: Create conda environment
      run: |
        conda create -n dedalus_env python=${{ matrix.python-version }} -y
        conda activate dedalus_env
        conda install -c conda-forge dedalus mpi4py h5py fftw matplotlib numpy scipy -y
        pip install pytest pytest-xdist

    - name: List directory contents
      run: ls -R

    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate dedalus_env
        pytest -v tests/test_exec.py


