name: Hartmann Flow Model Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        python-version: ${{ matrix.python-version }}

    - name: Install dedalus dependencies
      run: |
        conda install -c conda-forge mpi4py h5py fftw

    - name: Install dedalus
      run: |
        pip install dedalus

    - name: Install pytest and pytest-xdist
      run: |
        pip install pytest pytest-xdist

    - name: Run tests
      run: pytest -n auto


